name: shop_app_clean_architecture
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  bloc: ^8.1.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  dartz: ^0.10.1
  get_it: ^7.2.0
  carousel_slider: ^4.1.1
  internet_connection_checker: ^0.0.1+4
  fluttertoast: ^8.0.9
  flutter_add_to_cart_button: ^1.1.0
  smooth_page_indicator: ^1.0.0+2
  hexcolor: ^2.0.7
  shimmer: ^2.0.0
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.3
  provider: ^6.0.3
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0




flutter:


  uses-material-design: true


  assets:
    - assets/images/onBoard1.png
    - assets/images/onBoard2.png
    - assets/images/onBoard3.png
    - assets/images/ic_cart.png
    - assets/images/empty-order.svg
    - assets/images/empty-cart.svg
    - assets/images/address.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

