name: shop_app_clean_architecture
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  bloc: ^8.1.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  dartz: ^0.10.1
  get_it: ^7.2.0
  carousel_slider: ^4.1.1
  internet_connection_checker: ^0.0.1+4
  fluttertoast: ^8.0.9
  flutter_add_to_cart_button: ^1.1.0
  smooth_page_indicator: ^1.0.0+2
  hexcolor: ^2.0.7
  shimmer: ^2.0.0
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.3
  provider: ^6.0.3
  flutter_secure_storage: ^8.0.0
  flutter_screenutil: ^5.7.0
  flutter_hooks: ^0.18.6
  go_router: ^8.0.5
  flutter_advanced_drawer: ^1.3.5
  dot_navigation_bar: ^1.0.2
  loading_animation_widget: ^1.2.0+4
  intl: ^0.18.1
  google_maps_flutter: ^2.3.0
  permission_handler: ^10.4.3
  location: ^5.0.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.18

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Mo-logo.png"
  adaptive_icon_background: "#FFFFFF"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/Mo-logo.png
flutter:
  uses-material-design: true

  assets:
    - assets/images/onBoard1.png
    - assets/images/onBoard2.png
    - assets/images/onBoard3.png
    - assets/images/ic_cart.png
    - assets/images/empty-order.svg
    - assets/images/empty-cart.svg
    - assets/images/address.svg
    - assets/images/Mo-logo.png
    - assets/images/google_logo.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

